swagger: "2.0"
info:
  title: "Storage API"
  version: "1.0.0"
  description: "API zur Verwaltung von Storage Items inklusive zugehöriger Nährstoff-Daten und Basket Items."
host: "localhost:5000"
basePath: "/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /basket:
    get:
      summary: "Get all basket items"
      description: "Gibt alle Basket Items zurück."
      responses:
        "200":
          description: "Liste der Basket Items"
          schema:
            type: array
            items:
              $ref: "#/definitions/BasketItem"
    post:
      summary: "Add a basket item"
      description: "Fügt ein neues Basket Item hinzu oder inkrementiert die Menge, falls das Item bereits existiert."
      parameters:
        - in: body
          name: body
          description: "Basket Item-Daten"
          required: true
          schema:
            $ref: "#/definitions/BasketItemInput"
      responses:
        "201":
          description: "Basket Item erfolgreich hinzugefügt"
          schema:
            $ref: "#/definitions/BasketItem"
        "400":
          description: "Ungültige Eingabedaten"
          schema:
            $ref: "#/definitions/Error"

  /basket/{item_id}:
    parameters:
      - name: item_id
        in: path
        description: "Die ID des Basket Items"
        required: true
        type: integer
    put:
      summary: "Update a basket item"
      description: "Aktualisiert die Menge (amount) eines Basket Items."
      parameters:
        - in: body
          name: body
          description: "Neuer Wert für amount"
          required: true
          schema:
            type: object
            properties:
              amount:
                type: integer
                example: 2
      responses:
        "201":
          description: "Basket Item erfolgreich aktualisiert"
          schema:
            $ref: "#/definitions/BasketItem"
        "400":
          description: "Ungültige Eingabedaten"
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: "Item not found"
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: "Delete a basket item"
      description: "Löscht ein Basket Item anhand der ID."
      responses:
        "200":
          description: "Basket Item erfolgreich gelöscht"
          schema:
            $ref: "#/definitions/BasketItem"
        "404":
          description: "Item not found"
          schema:
            $ref: "#/definitions/Error"

  /items/bulk:
    post:
      summary: "Add multiple storage items at once"
      description: "Fügt mehrere Storage Items gleichzeitig hinzu, inklusive deren Nährstoffdaten, sofern vorhanden."
      parameters:
        - in: body
          name: body
          description: "Liste von Storage Items, die hinzugefügt werden sollen."
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/StorageItemInput"
      responses:
        "201":
          description: "Items added successfully"
          schema:
            type: object
            properties:
              message:
                type: string
        "400":
          description: "Invalid input data"
          schema:
            $ref: "#/definitions/Error"
        "409":
          description: "Conflict - duplicate item exists"
          schema:
            $ref: "#/definitions/Error"

  /items:
    get:
      summary: "Get all storage items"
      description: "Gibt alle Storage Items zurück. Optional kann über den Query-Parameter `q` nach Namen gesucht werden."
      parameters:
        - in: query
          name: q
          description: "Suchbegriff, um Items anhand des Namens zu filtern."
          required: false
          type: string
      responses:
        "200":
          description: "Liste der Storage Items"
          schema:
            type: array
            items:
              $ref: "#/definitions/StorageItem"
    post:
      summary: "Add a new storage item"
      description: "Fügt ein neues Storage Item hinzu. Optional können auch Nährstoff-Daten mitgesendet werden."
      parameters:
        - in: body
          name: body
          description: "Das hinzuzufügende Storage Item."
          required: true
          schema:
            $ref: "#/definitions/StorageItemInput"
      responses:
        "201":
          description: "Item added successfully"
          schema:
            type: object
            properties:
              message:
                type: string
        "400":
          description: "Invalid input data"
          schema:
            $ref: "#/definitions/Error"
        "409":
          description: "Item with the same name, storageLocation, and unit already exists."
          schema:
            $ref: "#/definitions/Error"

  /items/{item_id}:
    put:
      summary: "Update an existing storage item"
      description: "Aktualisiert ein bestehendes Storage Item anhand der übergebenen ID."
      parameters:
        - name: item_id
          in: path
          description: "Die ID des zu aktualisierenden Storage Items."
          required: true
          type: integer
        - in: body
          name: body
          description: "Die zu aktualisierenden Felder des Storage Items."
          required: true
          schema:
            $ref: "#/definitions/StorageItemUpdate"
      responses:
        "200":
          description: "Item updated successfully"
          schema:
            type: object
            properties:
              message:
                type: string
        "400":
          description: "Invalid input data"
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: "Item not found"
          schema:
            $ref: "#/definitions/Error"
    get:
      summary: "Get a specific storage item by ID"
      description: "Gibt ein spezifisches Storage Item zurück, basierend auf der übergebenen ID."
      parameters:
        - name: item_id
          in: path
          description: "Die ID des abzurufenden Storage Items."
          required: true
          type: integer
      responses:
        "200":
          description: "Das Storage Item mit seinen Details"
          schema:
            $ref: "#/definitions/StorageItem"
        "404":
          description: "Item not found"
          schema:
            $ref: "#/definitions/Error"

  /items/{item_id}/nutrients:
    put:
      summary: "Update the nutrients for a specific storage item"
      description: "Aktualisiert die Nährstoff-Daten für das Storage Item mit der angegebenen ID. Bestehende Nährstoffdaten werden ersetzt."
      parameters:
        - name: item_id
          in: path
          description: "Die ID des Storage Items, dessen Nährstoff-Daten aktualisiert werden sollen."
          required: true
          type: integer
        - in: body
          name: body
          description: "Die neuen Nährstoff-Daten für das Storage Item."
          required: true
          schema:
            $ref: "#/definitions/NutrientInput"
      responses:
        "200":
          description: "Nutrients updated successfully"
          schema:
            type: object
            properties:
              message:
                type: string
        "400":
          description: "Invalid input data"
          schema:
            $ref: "#/definitions/Error"
        "404":
          description: "Item not found"
          schema:
            $ref: "#/definitions/Error"

definitions:
  StorageItemInput:
    type: object
    required:
      - name
      - amount
      - lowestAmount
      - midAmount
      - unit
      - storageLocation
    properties:
      name:
        type: string
      amount:
        type: integer
      categories:
        type: array
        items:
          type: string
      lowestAmount:
        type: integer
      midAmount:
        type: integer
      unit:
        type: string
      packageQuantity:
        type: integer
      packageUnit:
        type: string
      storageLocation:
        type: string
      icon:
        type: string
      nutrients:
        $ref: "#/definitions/NutrientInput"

  StorageItemUpdate:
    type: object
    properties:
      name:
        type: string
      amount:
        type: integer
      categories:
        type: array
        items:
          type: string
      lowestAmount:
        type: integer
      midAmount:
        type: integer
      unit:
        type: string
      packageQuantity:
        type: integer
      packageUnit:
        type: string
      storageLocation:
        type: string
      icon:
        type: string

  StorageItem:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      amount:
        type: integer
      categories:
        type: array
        items:
          type: string
      lowestAmount:
        type: integer
      midAmount:
        type: integer
      unit:
        type: string
      packageQuantity:
        type: integer
      packageUnit:
        type: string
      storageLocation:
        type: string
      icon:
        type: string
      nutrients:
        $ref: "#/definitions/Nutrient"

  NutrientInput:
    type: object
    required:
      - description
      - unit
      - amount
    properties:
      description:
        type: string
      unit:
        type: string
        description: "Einheit der Nährwertangaben (z.B. 'g' oder 'ml')."
      amount:
        type: number
        description: "Bezugsmenge, z.B. 100 für 'pro 100g' bzw. 'pro 100ml'."
      values:
        type: array
        items:
          $ref: "#/definitions/NutrientValueInput"

  Nutrient:
    type: object
    properties:
      id:
        type: integer
      description:
        type: string
      unit:
        type: string
      amount:
        type: number
      values:
        type: array
        items:
          $ref: "#/definitions/NutrientValue"

  NutrientValueInput:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      color:
        type: string
      values:
        type: array
        items:
          $ref: "#/definitions/NutrientTypeInput"

  NutrientValue:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      color:
        type: string
      values:
        type: array
        items:
          $ref: "#/definitions/NutrientType"

  NutrientTypeInput:
    type: object
    required:
      - typ
      - value
    properties:
      typ:
        type: string
        description: "Angabe des Einheitentyps, z.B. 'kcal', 'KJ' oder 'g'."
      value:
        type: number

  NutrientType:
    type: object
    properties:
      id:
        type: integer
      typ:
        type: string
      value:
        type: number

  BasketItemInput:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      categories:
        type: array
        items:
          type: string
      icon:
        type: string

  BasketItem:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      amount:
        type: integer
      categories:
        type: array
        items:
          type: string
      icon:
        type: string

  Error:
    type: object
    properties:
      error:
        type: string
